// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using GHLearning.CleanArchitecture.Infrastructure.Entities.Configurations;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using GHLearning.CleanArchitecture.Infrastructure.Entities.Models;
#nullable enable

namespace GHLearning.CleanArchitecture.Infrastructure.Entities;

public partial class SampleContext : DbContext
{
    public SampleContext(DbContextOptions<SampleContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TodoItem> TodoItems { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("utf8mb4_general_ci")
            .HasCharSet("utf8mb4");

        modelBuilder.ApplyConfiguration(new Configurations.TodoItemConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.UserConfiguration());
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
