// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using GHLearning.CleanArchitecture.Migrations.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace GHLearning.CleanArchitecture.Migrations.Entities.Configurations
{
    public partial class TodoItemConfiguration : IEntityTypeConfiguration<TodoItem>
    {
        public void Configure(EntityTypeBuilder<TodoItem> entity)
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("todo_items");

            entity.HasIndex(e => e.UserId, "fk_todo_items_users");

            entity.Property(e => e.Id)
                .HasColumnName("id")
                .UseCollation("ascii_general_ci")
                .HasCharSet("ascii");
            entity.Property(e => e.CompletedAt)
                .HasMaxLength(6)
                .HasColumnName("completed_at");
            entity.Property(e => e.CreatedAt)
                .HasMaxLength(6)
                .HasColumnName("created_at");
            entity.Property(e => e.Description)
                .HasColumnType("text")
                .HasColumnName("description");
            entity.Property(e => e.DueDate)
                .HasMaxLength(6)
                .HasColumnName("due_date");
            entity.Property(e => e.IsCompleted)
                .HasColumnType("tinyint(4)")
                .HasColumnName("is_completed");
            entity.Property(e => e.Labels)
                .HasColumnType("text")
                .HasColumnName("labels");
            entity.Property(e => e.Priority)
                .HasColumnType("int(11)")
                .HasColumnName("priority");
            entity.Property(e => e.UserId)
                .HasColumnName("user_id")
                .UseCollation("ascii_general_ci")
                .HasCharSet("ascii");

            entity.HasOne(d => d.User).WithMany(p => p.TodoItems)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_todo_items_users");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TodoItem> entity);
    }
}
