// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using GHLearning.CleanArchitecture.Infrastructure.Entities;
using GHLearning.CleanArchitecture.Infrastructure.Entities.Models;

namespace GHLearning.CleanArchitecture.Infrastructure.Entities.Models;

public partial class TodoItem
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public string Description { get; set; } = null!;

    public DateTime? DueDate { get; set; }

    public string Labels { get; set; } = null!;

    public sbyte IsCompleted { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public int Priority { get; set; }

    public virtual User User { get; set; } = null!;
}
