// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using GHLearning.CleanArchitecture.Infrastructure.Entities.Models;
using GHLearning.CleanArchitecture.Infrastructure.Entities;

namespace GHLearning.CleanArchitecture.Infrastructure.Entities.Models;

public partial class User
{
    public Guid Id { get; set; }

    public string Email { get; set; } = null!;

    public string FirstName { get; set; } = null!;

    public string LastName { get; set; } = null!;

    public string PasswordHash { get; set; } = null!;

    public virtual ICollection<TodoItem> TodoItems { get; set; } = new List<TodoItem>();
}
