name: Codecov

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET 9.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Run tests and collect coverage
        run: dotnet test --configuration Release --collect:"Code Coverage" --results-directory $(Build.ArtifactStagingDirectory)

      - name: Install Codecov
        run: curl -s https://codecov.io/bash | bash

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
